"""
File filtering logic for code extraction.

Handles size, content, path-based, and quality filters.
"""

import re
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class FilterConfig:
    """Configuration for file filtering."""
    # Size filters
    min_size: int = 500  # bytes
    max_size: int = 100_000  # bytes
    min_lines: int = 10
    max_line_length: int = 1000

    # Content filters
    exclude_autogenerated: bool = True
    exclude_vendored: bool = True
    exclude_tests: bool = False
    exclude_minified: bool = True
    exclude_data_files: bool = True
    exclude_non_utf8: bool = True

    # Thresholds
    max_comment_ratio: float = 0.7

    # Path patterns
    excluded_paths: list = field(default_factory=lambda: [
        'vendor/', 'node_modules/', 'third_party/', 'external/',
        'dist/', 'build/', 'out/', 'target/',
        '__pycache__/', '.gradle/', '.idea/', '.vscode/',
        'venv/', 'env/', '.env/', 'site-packages/',
    ])

    # Auto-generated markers
    autogen_markers: list = field(default_factory=lambda: [
        'DO NOT EDIT', 'DO NOT MODIFY', 'Generated by', 'Auto-generated',
        '@generated', 'automatically generated', 'THIS FILE IS GENERATED',
        'Code generated by', 'Generated from', 'AUTOGENERATED',
    ])

    # Test patterns
    test_patterns: list = field(default_factory=lambda: [
        r'test_.*\.py$',
        r'.*_test\.py$',
        r'.*_test\.go$',
        r'.*Test\.java$',
        r'.*\.test\.[jt]sx?$',
        r'.*\.spec\.[jt]sx?$',
        r'tests?/',
        r'__tests__/',
        r'spec/',
    ])

    # Data file patterns (files that are mostly data, not logic)
    data_patterns: list = field(default_factory=lambda: [
        r'fixtures?/',
        r'mock/',
        r'stub/',
        r'sample/',
        r'example/',
        r'data/',
    ])


@dataclass
class FilterResult:
    """Result of filter check."""
    passed: bool
    reason: Optional[str] = None


class FileFilter:
    """Apply configurable filters to files."""

    def __init__(self, config: FilterConfig):
        self.config = config
        self._compile_patterns()

    def _compile_patterns(self):
        """Pre-compile regex patterns for efficiency."""
        self.test_patterns = [
            re.compile(p, re.IGNORECASE) for p in self.config.test_patterns
        ]
        self.data_patterns = [
            re.compile(p, re.IGNORECASE) for p in self.config.data_patterns
        ]

    def check(self, file_path: str, content: str) -> FilterResult:
        """
        Apply all filters to a file.

        Returns FilterResult indicating if file passed all filters.
        """
        # Size check (bytes)
        content_size = len(content.encode('utf-8', errors='replace'))
        if content_size < self.config.min_size:
            return FilterResult(False, f"File too small: {content_size} bytes")
        if content_size > self.config.max_size:
            return FilterResult(False, f"File too large: {content_size} bytes")

        # Line count check
        lines = content.split('\n')
        non_empty_lines = [l for l in lines if l.strip()]
        if len(non_empty_lines) < self.config.min_lines:
            return FilterResult(False, f"Too few lines: {len(non_empty_lines)}")

        # Minified check (long lines)
        if self.config.exclude_minified:
            result = self._check_minified(lines)
            if not result.passed:
                return result

        # Path-based exclusions
        if self.config.exclude_vendored:
            result = self._check_vendored(file_path)
            if not result.passed:
                return result

        # Test file check
        if self.config.exclude_tests:
            result = self._check_test_file(file_path)
            if not result.passed:
                return result

        # Auto-generated check
        if self.config.exclude_autogenerated:
            result = self._check_autogenerated(content)
            if not result.passed:
                return result

        # Data file check
        if self.config.exclude_data_files:
            result = self._check_data_file(file_path, content)
            if not result.passed:
                return result

        # UTF-8 check
        if self.config.exclude_non_utf8:
            result = self._check_utf8(content)
            if not result.passed:
                return result

        return FilterResult(True)

    def _check_minified(self, lines: list[str]) -> FilterResult:
        """Check if file appears to be minified."""
        long_lines = 0
        total_lines = 0

        for line in lines:
            if not line.strip():
                continue
            total_lines += 1
            if len(line) > self.config.max_line_length:
                long_lines += 1

        # If more than 10% of lines are very long, likely minified
        if total_lines > 0 and (long_lines / total_lines) > 0.1:
            return FilterResult(False, "Appears to be minified")

        return FilterResult(True)

    def _check_vendored(self, file_path: str) -> FilterResult:
        """Check if file is in a vendored/third-party directory."""
        file_path_lower = file_path.lower().replace('\\', '/')

        for pattern in self.config.excluded_paths:
            if pattern.lower() in file_path_lower:
                return FilterResult(False, f"Vendored/excluded path: {pattern}")

        return FilterResult(True)

    def _check_test_file(self, file_path: str) -> FilterResult:
        """Check if file is a test file."""
        for pattern in self.test_patterns:
            if pattern.search(file_path):
                return FilterResult(False, "Test file")

        return FilterResult(True)

    def _check_autogenerated(self, content: str) -> FilterResult:
        """Check if file appears to be auto-generated."""
        # Check first 50 lines for auto-generated markers
        lines = content.split('\n')[:50]
        header = '\n'.join(lines).upper()

        for marker in self.config.autogen_markers:
            if marker.upper() in header:
                return FilterResult(False, f"Auto-generated: found '{marker}'")

        # Check for common auto-generated patterns
        autogen_patterns = [
            r'generated\s+by\s+\w+',
            r'this\s+file\s+is\s+generated',
            r'auto[-_]?generated',
            r'machine[-_]?generated',
            r'DO\s+NOT\s+(EDIT|MODIFY)',
        ]

        for pattern in autogen_patterns:
            if re.search(pattern, header, re.IGNORECASE):
                return FilterResult(False, f"Auto-generated: matches pattern")

        return FilterResult(True)

    def _check_data_file(self, file_path: str, content: str) -> FilterResult:
        """Check if file is primarily data rather than code."""
        # Check path patterns
        for pattern in self.data_patterns:
            if pattern.search(file_path):
                return FilterResult(False, "Data/fixture file path")

        # Check content patterns - large arrays/dicts with mostly literals
        # This is a heuristic: if file has very high ratio of brackets/braces
        # and string/number literals, it's likely data

        lines = content.split('\n')
        non_empty_lines = [l for l in lines if l.strip()]

        if len(non_empty_lines) < 10:
            return FilterResult(True)

        # Count lines that look like data (string literals, numbers, brackets)
        data_line_pattern = re.compile(
            r'^\s*[\[\]\{\},:\'"0-9\s\-\.]+\s*$|'  # JSON-like
            r'^\s*["\'][^"\']*["\']\s*[,:]?\s*$|'  # String literal
            r'^\s*\d+[\.,]?\d*\s*[,]?\s*$'  # Number
        )

        data_lines = sum(1 for line in non_empty_lines if data_line_pattern.match(line))
        data_ratio = data_lines / len(non_empty_lines)

        if data_ratio > 0.7:
            return FilterResult(False, f"Appears to be data file ({data_ratio:.0%} data lines)")

        return FilterResult(True)

    def _check_utf8(self, content: str) -> FilterResult:
        """Check if content is valid UTF-8."""
        try:
            content.encode('utf-8')
            return FilterResult(True)
        except UnicodeEncodeError:
            return FilterResult(False, "Invalid UTF-8 encoding")


def is_likely_minified(content: str, threshold: int = 500) -> bool:
    """
    Quick check if content appears to be minified.
    Returns True if average line length exceeds threshold.
    """
    lines = [l for l in content.split('\n') if l.strip()]
    if not lines:
        return False

    avg_length = sum(len(l) for l in lines) / len(lines)
    return avg_length > threshold


def has_syntax_errors(content: str, language: str) -> bool:
    """
    Check if code has obvious syntax errors.
    Only implemented for Python currently.
    """
    if language.lower() == 'python':
        try:
            compile(content, '<string>', 'exec')
            return False
        except SyntaxError:
            return True

    # For other languages, we'd need external parsers
    return False


def estimate_duplication_ratio(content: str, min_line_length: int = 20) -> float:
    """
    Estimate the ratio of duplicated lines in the content.
    Only considers lines longer than min_line_length.
    """
    lines = [l.strip() for l in content.split('\n')
             if len(l.strip()) >= min_line_length]

    if len(lines) < 2:
        return 0.0

    seen = set()
    duplicates = 0

    for line in lines:
        if line in seen:
            duplicates += 1
        else:
            seen.add(line)

    return duplicates / len(lines)
