from dataclasses import dataclass, field
from typing import Optional, List
from pathlib import Path
from datetime import datetime

@dataclass()
class MiningConfig:
    """
    Controls what we mine and where we write it.
    """
    # File Paths:
    data_base_path: Path = Path("data").resolve()
    output_base_path: Path = Path("output").resolve()
    repo_urls_file_path: Path = data_base_path / 'repo_links.txt'   # path to file containing git repos to drill
    output_csv_path: Path = output_base_path / 'repo_data.csv'      # path to output file from pydriller
    clone_repo_to: Path = data_base_path / 'temp'                   # path to where pydriller stores temporary commits
    checkpoint_dir: Path = output_base_path / 'repo_checkpoints'    # path to per-repo CSV checkpoints
    metadata_csv: Path = data_base_path / 'repos_dataset.csv'
    # Date Filters:
    date_since: str = "1980-01-01"          # ISO date string formatted as "YYYY-mm-dd" indicating earliest date to grab commits from
    date_to: str = "2030-12-31"             # ISO date string formatted as "YYYY-mm-dd" indicating latest date to grab commits from
    
    # Commit Filters:
    only_in_main_branch: bool = False       # only analyze commits from main
    only_no_merge: bool = True              # only analyze commits that are not merges
    only_in_branch: Optional[str] = None    # only analyze commits in this branch (e.g. main)
    only_releases: bool = False             # only analyze commits that from 'release' versions
    only_code_files: bool = True            # whitelists files based on extensions listed in `consts/code_file_exts.py`

    # Commit Sampling:
    min_commit_interval_days: int = 0       # min days between grabbed commits (0 = grab all)
    commit_skip: int = 5                   # take every Nth commit (0 or 1 = no skip, 2 = every 2nd, etc.)
    min_repo_commits: int = 30              # min number of commits for a repo to be considered for mining
    min_branch_commits: int = 10            # min number of commits for a branch to be analyzed

    # File Size Filters:
    max_repo_size_mb: int = 1000             # max size of a repo to analyze (MB)
    min_file_size: int = 500                # min file size in bytes
    max_file_size: int = 100_000            # max file size in bytes (100KB)
    min_lines: int = 10                     # min number of lines for a file to be included
    max_line_length: int = 10000             # max line length (for minified detection)

    # Content Filters:
    exclude_autogenerated: bool = True      # exclude auto-generated files
    exclude_vendored: bool = True           # exclude vendored/third-party code
    exclude_tests: bool = False             # exclude test files
    exclude_minified: bool = True           # exclude minified files
    max_comment_ratio: float = 0.7          # exclude files with >70% comments

    # Content Options:
    include_diff: bool = True               # include the diff of files in each commit
    include_src_code: bool = True           # include the src code of files in each commit
    include_metrics: bool = True            # compute and include code metrics

    # Path patterns to exclude (vendored paths)
    excluded_paths: List[str] = field(default_factory=lambda: [
        'vendor/', 'node_modules/', 'third_party/', 'external/',
        'dist/', 'build/', 'out/', 'target/',
        '__pycache__/', '.gradle/', '.idea/', '.vscode/',
        'venv/', 'env/', '.env/', 'site-packages/',
    ])

    # Auto-generated markers
    autogen_markers: List[str] = field(default_factory=lambda: [
        'DO NOT EDIT', 'DO NOT MODIFY', 'Generated by', 'Auto-generated',
        '@generated', 'automatically generated', 'THIS FILE IS GENERATED',
        'Code generated by', 'Generated from', 'AUTOGENERATED',
    ])

    # Parallelization:
    num_workers: int = 1                    # threads for parallel commit processing (1 = sequential)
    max_cloned_repos: int = 10              # max repos to clone ahead of processing (clone queue size)
    parallel_cloning: bool = True           # clone repos in background while processing (works even with num_workers=1)
    commit_timeout: int = 5                 # timeout in seconds for processing a single commit
    batch_timeout: int = 120                # timeout in seconds for a batch of commits (per branch)
    repo_timeout: int = 600                 # timeout in seconds for processing an entire repo

    def __post_init__(self):
        """Convert date strings to datetime objects after initialization."""
        if isinstance(self.date_since, str):
            self.date_since = datetime.strptime(self.date_since, '%Y-%m-%d')
        if isinstance(self.date_to, str):
            self.date_to = datetime.strptime(self.date_to, '%Y-%m-%d')


# global config objects
mining_cfg = MiningConfig()
