"""
Extract code from GitHub repos for AI detection analysis.

For each repo, iterates through branches with sufficient commits,
extracts full file content and diffs, computes metrics, and saves to CSV.
"""

import argparse
import csv
import os
import re
import subprocess
import sys
import tempfile
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

# Add project root to path for imports
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd
from tqdm import tqdm

from utils.code_metrics import (
    compute_loc,
    compute_comment_density,
    compute_boilerplate_score,
    compute_complexity_metrics,
)
from utils.file_filters import FileFilter, FilterConfig
from utils.file_classifier import classify_file_type


@dataclass
class ExtractionConfig:
    """Configuration for code extraction."""
    # Size filters
    min_file_size: int = 500  # bytes
    max_file_size: int = 100_000  # bytes (100KB)
    min_lines: int = 10
    max_line_length: int = 1000  # flags minified code

    # Content filters
    exclude_autogenerated: bool = True
    exclude_vendored: bool = True
    exclude_tests: bool = False  # Keep tests separate by default
    exclude_minified: bool = True
    exclude_data_files: bool = True
    exclude_non_utf8: bool = True
    exclude_syntax_errors: bool = False  # May want to keep these

    # Thresholds
    max_comment_ratio: float = 0.7  # Exclude if >70% comments
    min_commit_count: int = 10  # Min commits for branch to be included

    # Commit sampling
    min_commit_interval_days: int = 0  # Min days between grabbed commits (0 = no filter)
    commit_skip: int = 0  # Take every Nth commit (0 = no skip, 1 = every commit)

    # Path patterns to exclude
    excluded_paths: list = field(default_factory=lambda: [
        'vendor/', 'node_modules/', 'third_party/', 'external/',
        'dist/', 'build/', 'out/', 'target/',
        '__pycache__/', '.gradle/', '.idea/', '.vscode/',
        'venv/', 'env/', '.env/', 'site-packages/',
    ])

    # Auto-generated markers
    autogen_markers: list = field(default_factory=lambda: [
        'DO NOT EDIT', 'DO NOT MODIFY', 'Generated by', 'Auto-generated',
        '@generated', 'automatically generated', 'THIS FILE IS GENERATED',
        'Code generated by', 'Generated from', 'AUTOGENERATED',
    ])

    # File extensions to include (per language)
    extensions_by_language: dict = field(default_factory=lambda: {
        'python': ['.py'],
        'javascript': ['.js', '.jsx', '.mjs'],
        'java': ['.java'],
        'c': ['.c', '.h'],
        'c++': ['.cpp', '.cc', '.cxx', '.hpp', '.hh', '.hxx', '.h'],
        'c#': ['.cs'],
        'go': ['.go'],
    })

    # Output settings
    output_dir: Path = Path('data/code_extracts')


def run_git_command(args: list[str], cwd: Path, timeout: int = 300) -> Optional[str]:
    """
    Run a git command and return stdout as string.
    Handles encoding issues gracefully.
    """
    try:
        result = subprocess.run(
            args,
            cwd=cwd,
            capture_output=True,
            timeout=timeout
        )
        if result.returncode != 0:
            return None
        # Decode with utf-8, replacing any problematic characters
        return result.stdout.decode('utf-8', errors='replace')
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, OSError):
        return None


def get_commit_timestamp(repo_dir: Path, commit_hash: str) -> Optional[int]:
    """Get Unix timestamp of a commit."""
    output = run_git_command(
        ['git', 'show', '-s', '--format=%ct', commit_hash],
        repo_dir
    )
    if not output:
        return None
    try:
        return int(output.strip())
    except ValueError:
        return None


def clone_repo(repo_url: str, dest_dir: Path, pbar: Optional[tqdm] = None) -> bool:
    """Clone a repository to the destination directory."""
    try:
        if pbar:
            pbar.set_postfix_str("Cloning...")
        subprocess.run(
            ['git', 'clone', '--quiet', repo_url, str(dest_dir)],
            check=True,
            capture_output=True,
            timeout=300  # 5 min timeout
        )
        return True
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, OSError) as e:
        return False


def get_branches_with_commits(repo_dir: Path, min_commits: int) -> list[tuple[str, int]]:
    """Get branches that have at least min_commits commits."""
    output = run_git_command(['git', 'branch', '-r'], repo_dir)
    if not output:
        return []

    branches = []
    for line in output.strip().split('\n'):
        branch = line.strip()
        if '->' in branch or not branch:
            continue

        count_output = run_git_command(
            ['git', 'rev-list', '--count', branch],
            repo_dir
        )
        if count_output:
            try:
                commit_count = int(count_output.strip())
                if commit_count >= min_commits:
                    branches.append((branch, commit_count))
            except ValueError:
                continue

    return branches


def get_commits(repo_dir: Path, branch: str) -> list[str]:
    """Get list of commit hashes for a branch."""
    output = run_git_command(
        ['git', 'log', branch, '--format=%H'],
        repo_dir
    )
    if not output:
        return []
    return [c for c in output.strip().split('\n') if c]


def get_files_in_commit(repo_dir: Path, commit_hash: str) -> list[str]:
    """Get list of files changed in a commit."""
    output = run_git_command(
        ['git', 'diff-tree', '--no-commit-id', '--name-only', '-r', commit_hash],
        repo_dir
    )
    if not output:
        return []
    return [f for f in output.strip().split('\n') if f]


def get_file_content_at_commit(repo_dir: Path, commit_hash: str, file_path: str) -> Optional[str]:
    """Get the full content of a file at a specific commit."""
    return run_git_command(
        ['git', 'show', f'{commit_hash}:{file_path}'],
        repo_dir
    )


def get_diff_added_lines(repo_dir: Path, commit_hash: str, file_path: str) -> Optional[str]:
    """Get only the added lines from a commit's diff for a specific file."""
    output = run_git_command(
        ['git', 'show', commit_hash, '--', file_path, '--format='],
        repo_dir
    )
    if not output:
        return None

    # Extract only added lines (lines starting with +, excluding +++ header)
    added_lines = []
    for line in output.split('\n'):
        if line.startswith('+') and not line.startswith('+++'):
            added_lines.append(line[1:])  # Remove the leading +

    return '\n'.join(added_lines) if added_lines else None


def extract_repo(
    repo_id: int,
    repo_url: str,
    repo_language: str,
    config: ExtractionConfig,
    file_filter: FileFilter,
    repo_pbar: tqdm,
    total_rows_counter: dict,
) -> Optional[Path]:
    """
    Extract code from a single repository.
    Returns path to output CSV or None if failed.
    """
    output_path = config.output_dir / f"repo_{repo_id}.csv"

    # Skip if already processed
    if output_path.exists():
        repo_pbar.set_postfix_str("Already processed, skipping")
        return output_path

    # Create temp directory for cloning
    with tempfile.TemporaryDirectory() as tmp_dir:
        repo_dir = Path(tmp_dir) / 'repo'

        repo_pbar.set_postfix_str("Cloning...")
        if not clone_repo(repo_url, repo_dir):
            repo_pbar.set_postfix_str("Clone failed")
            return None

        # Get valid extensions for this language
        valid_extensions = config.extensions_by_language.get(
            repo_language.lower(), []
        )
        if not valid_extensions:
            repo_pbar.set_postfix_str(f"No extensions for {repo_language}")
            return None

        rows = []

        # Get branches with sufficient commits
        repo_pbar.set_postfix_str("Finding branches...")
        branches = get_branches_with_commits(repo_dir, config.min_commit_count)

        if not branches:
            repo_pbar.set_postfix_str("No valid branches")
            return None

        # Process branches
        branch_pbar = tqdm(
            branches,
            desc="    Branches",
            leave=False,
            unit="branch",
            position=1
        )

        for branch, commit_count in branch_pbar:
            branch_name = branch.replace('origin/', '')
            branch_pbar.set_postfix_str(f"{branch_name}")

            commits = get_commits(repo_dir, branch)
            if not commits:
                continue

            # Apply commit skip filter (take every Nth)
            if config.commit_skip > 0:
                commits = commits[::config.commit_skip]

            # Process commits
            commit_pbar = tqdm(
                commits,
                desc="      Commits",
                leave=False,
                unit="commit",
                position=2
            )

            last_grabbed_timestamp = None
            min_interval_seconds = config.min_commit_interval_days * 24 * 60 * 60

            for commit_hash in commit_pbar:
                commit_pbar.set_postfix_str(f"{commit_hash[:8]} | Total: {total_rows_counter['count']}")

                # Apply time-based filtering
                if min_interval_seconds > 0:
                    commit_ts = get_commit_timestamp(repo_dir, commit_hash)
                    if commit_ts is not None:
                        if last_grabbed_timestamp is not None:
                            # Skip if not enough time has passed
                            if abs(last_grabbed_timestamp - commit_ts) < min_interval_seconds:
                                continue
                        last_grabbed_timestamp = commit_ts

                files = get_files_in_commit(repo_dir, commit_hash)
                if not files:
                    continue

                # Filter to valid extensions first
                valid_files = [
                    f for f in files
                    if any(f.endswith(ext) for ext in valid_extensions)
                ]

                if not valid_files:
                    continue

                # Process files
                file_pbar = tqdm(
                    valid_files,
                    desc="        Files",
                    leave=False,
                    unit="file",
                    position=3
                )

                for file_path in file_pbar:
                    file_pbar.set_postfix_str(Path(file_path).name[:30])

                    # Get full file content
                    full_content = get_file_content_at_commit(repo_dir, commit_hash, file_path)
                    if full_content is None:
                        continue

                    # Apply filters
                    filter_result = file_filter.check(file_path, full_content)
                    if not filter_result.passed:
                        continue

                    # Get diff (added lines only)
                    diff_content = get_diff_added_lines(repo_dir, commit_hash, file_path)

                    # Compute metrics
                    full_loc = compute_loc(full_content)
                    diff_loc = compute_loc(diff_content) if diff_content else 0
                    comment_density = compute_comment_density(full_content, repo_language)
                    boilerplate_score = compute_boilerplate_score(full_content, repo_language)
                    complexity = compute_complexity_metrics(full_content, repo_language)
                    file_type = classify_file_type(file_path, full_content)

                    row = {
                        'repo_id': repo_id,
                        'branch': branch,
                        'commit_hash': commit_hash,
                        'file_path': file_path,
                        'file_type': file_type,
                        'full_code': full_content,
                        'diff_added': diff_content or '',
                        'loc_full': full_loc,
                        'loc_diff': diff_loc,
                        'comment_density': comment_density,
                        'boilerplate_score': boilerplate_score,
                        'cyclomatic_complexity': complexity.get('cyclomatic', None),
                        'cognitive_complexity': complexity.get('cognitive', None),
                        'max_nesting_depth': complexity.get('max_nesting', None),
                        # Granularity columns - NA for now
                        'snippets_fixed_lines': None,
                        'snippets_functions': None,
                        'snippets_classes': None,
                    }
                    rows.append(row)
                    total_rows_counter['count'] += 1

                file_pbar.close()
            commit_pbar.close()
        branch_pbar.close()

        if rows:
            # Save to CSV
            config.output_dir.mkdir(parents=True, exist_ok=True)
            df = pd.DataFrame(rows)
            df.to_csv(output_path, index=False)
            repo_pbar.set_postfix_str(f"Saved {len(rows)} rows | Total: {total_rows_counter['count']}")
            return output_path
        else:
            repo_pbar.set_postfix_str(f"No valid files | Total: {total_rows_counter['count']}")
            return None


def main():
    parser = argparse.ArgumentParser(description='Extract code from GitHub repos')

    # Input/output
    parser.add_argument('--metadata-csv', type=str, default='data/repos_dataset.csv',
                        help='Path to repos metadata CSV')
    parser.add_argument('--output-dir', type=str, default='data/code_extracts',
                        help='Output directory for extracted code CSVs')

    # Size filters
    parser.add_argument('--min-file-size', type=int, default=500,
                        help='Minimum file size in bytes')
    parser.add_argument('--max-file-size', type=int, default=100000,
                        help='Maximum file size in bytes')
    parser.add_argument('--min-lines', type=int, default=10,
                        help='Minimum number of lines')
    parser.add_argument('--max-line-length', type=int, default=1000,
                        help='Maximum line length (for minified detection)')

    # Content filters
    parser.add_argument('--include-autogenerated', action='store_true',
                        help='Include auto-generated files')
    parser.add_argument('--include-vendored', action='store_true',
                        help='Include vendored/third-party code')
    parser.add_argument('--exclude-tests', action='store_true',
                        help='Exclude test files')
    parser.add_argument('--include-minified', action='store_true',
                        help='Include minified files')
    parser.add_argument('--include-non-utf8', action='store_true',
                        help='Include non-UTF8 files')

    # Thresholds
    parser.add_argument('--max-comment-ratio', type=float, default=0.7,
                        help='Maximum comment ratio (0-1)')
    parser.add_argument('--min-commits', type=int, default=10,
                        help='Minimum commits for branch inclusion')

    # Commit sampling
    parser.add_argument('--min-commit-interval-days', type=int, default=0,
                        help='Min days between grabbed commits (0 = grab all)')
    parser.add_argument('--commit-skip', type=int, default=0,
                        help='Take every Nth commit (0 or 1 = no skip, 2 = every 2nd, etc.)')

    # Subset selection
    parser.add_argument('--repo-ids', type=int, nargs='+',
                        help='Specific repo IDs to process')
    parser.add_argument('--limit', type=int,
                        help='Limit number of repos to process')
    parser.add_argument('--domain', type=str,
                        help='Filter by domain')
    parser.add_argument('--language', type=str,
                        help='Filter by language')

    args = parser.parse_args()

    # Build config
    config = ExtractionConfig(
        min_file_size=args.min_file_size,
        max_file_size=args.max_file_size,
        min_lines=args.min_lines,
        max_line_length=args.max_line_length,
        exclude_autogenerated=not args.include_autogenerated,
        exclude_vendored=not args.include_vendored,
        exclude_tests=args.exclude_tests,
        exclude_minified=not args.include_minified,
        exclude_non_utf8=not args.include_non_utf8,
        max_comment_ratio=args.max_comment_ratio,
        min_commit_count=args.min_commits,
        min_commit_interval_days=args.min_commit_interval_days,
        commit_skip=args.commit_skip if args.commit_skip > 1 else 0,
        output_dir=Path(args.output_dir),
    )

    # Build filter config
    filter_config = FilterConfig(
        min_size=config.min_file_size,
        max_size=config.max_file_size,
        min_lines=config.min_lines,
        max_line_length=config.max_line_length,
        exclude_autogenerated=config.exclude_autogenerated,
        exclude_vendored=config.exclude_vendored,
        exclude_tests=config.exclude_tests,
        exclude_minified=config.exclude_minified,
        exclude_non_utf8=config.exclude_non_utf8,
        max_comment_ratio=config.max_comment_ratio,
        excluded_paths=config.excluded_paths,
        autogen_markers=config.autogen_markers,
    )
    file_filter = FileFilter(filter_config)

    # Load metadata
    df = pd.read_csv(args.metadata_csv)

    # Apply filters
    if args.repo_ids:
        df = df[df['id'].isin(args.repo_ids)]
    if args.domain:
        df = df[df['domain'] == args.domain]
    if args.language:
        df = df[df['language'] == args.language]
    if args.limit:
        df = df.head(args.limit)

    # Process each repo with progress bar
    successful = 0
    failed = 0
    total_rows_counter = {'count': 0}  # Use dict to allow mutation in nested function

    repo_pbar = tqdm(
        df.iterrows(),
        total=len(df),
        desc="Repos",
        unit="repo",
        position=0
    )

    for _, row in repo_pbar:
        repo_id = row['id']
        repo_url = row['clone_url']
        repo_language = row['language']
        repo_name = row.get('name', str(repo_id))

        repo_pbar.set_description(f"Repo: {repo_name[:30]}")
        repo_pbar.set_postfix_str(f"Total rows: {total_rows_counter['count']}")

        result = extract_repo(repo_id, repo_url, repo_language, config, file_filter, repo_pbar, total_rows_counter)
        if result:
            successful += 1
        else:
            failed += 1

    repo_pbar.close()
    print(f"\nComplete: {successful} successful, {failed} failed")
    print(f"Total rows extracted: {total_rows_counter['count']}")


if __name__ == '__main__':
    main()
